version: '2'
services:

  scraper:
    build: .
    container_name: scraper
    depends_on:
      - db


  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=snowpackDB
    container_name: postgres


volumes:
  postgres_data:
