version: '3'
services:
  web: &python
    build: ./djangosnotel
    command: python manage.py runserver 0.0.0.0:8000
    container_name: djangoapp
    volumes:
      - ./djangosnotel/:/usr/src/app/
      - ~/.aws/:/root/.aws:ro
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev-sample


volumes:
  postgres_data:
