# Generated by Django 2.2.8 on 2020-05-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowpack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basins',
            fields=[
                ('basin_id', models.AutoField(primary_key=True, serialize=False)),
                ('basin_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'basins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('elevation', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnowpackData',
            fields=[
                ('data_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('snow_current', models.IntegerField()),
                ('water_current', models.IntegerField()),
                ('water_avg', models.IntegerField()),
                ('water_pct_avg', models.IntegerField()),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snowpack.Locations')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
    ]
